############### PREVENT WATER BUILDUP ###############

#Prevents liquids from going outside BW arena
#Will not affect other gamemodes
Prevent-Liquid-Build-Up: true

############### DISABLE EMPTY BASE GENERATORS ###############

#Disable generators in empty bases
#Range = distance from team spawn to spawner
Disable-Unused-Gens:
  Enabled: false
  Range: 6
  Gen-Types:
    - 'IRON_INGOT'
    - 'GOLD_INGOT'

############### Final Kill ###############

#Final Kill FinalKillMessage:
#COMMING IN THE NEXT VERSION OF MBEDWARS (Beta 7)
Final-Kill-Message: false

#Players get a lightning blot at their location of death if it is a final kill
Final-Kill-Strike:
  Enabled: false

############### FIREBALL BLOCK WHITELIST ###############

#Blocks that fireballs will not destroy (Overrides MBedwars' BlackList)
FireballWhitelist:
  Enabled: true
  Blocks:
    - ENDER_STONE
    - END_STONE

############### BUY-MESSAGE ###############

#FinalKillMessage sent to players when they purchase an item
#Placeholders: %amount% %product%
BuyMessage:
  Enabled: true
  Message: '&aYou Purchased &6%product% x%amount%'

############### GEN TIERS ###############

#Teirs can be configured in the gen-tiers.yml
Gen-Tiers-Enabled: false


############### TNT AUTO IGNITE ###############

#WARNING!!! If you enable this MAKE SURE MBedwars' tnt-autoignite is FALSE
TNT:
  Auto-Ignite: false
  Delay: 4

############### REMOVE ON USE ###############
Empty-Buckets: true
Empty-Potions: true

############### TOP KILLER MESSAGE ###############
Top-Killer-Message-Enabled: true

# 1 - we will use No-Top-Killer-FinalKillMessage to replace the line
# 2 - we will replace only the name to No-Top-Killer-Name
# 3 - we will remove the line completely
No-Top-Killer-Display-Type: 3

#Set No-Top-Killer-Display-Type to 1
No-Top-Killer-Message: 'This Spot Is Empty!'

#Set No-Top-Killer-Display-Type to 2
No-Top-Killer-Name: '----------'

#No Top killers FinalKillMessage
No-Top-Killers-Message:
  - ''
  - 'No top killers today :/'
  - ''

# PLACEHOLDERS:
# %Killer-1-Name% %Killer-2-Name% %Killer-3-Name%
# %Killer-1-Amount% %Killer-2-Amount% %Killer-3-Amount%
Top-Killer-Message:
  - '&a&l-------------------------------'
  - '                &lBedWars'
  - ''
  - '    &e&l1st Killer &7- %Killer-1-Name% - %Killer-1-Amount%'
  - '    &6&l2nd Killer &7- %Killer-2-Name% - %Killer-2-Amount%'
  - '    &c&l3rd Killer &7- %Killer-3-Name% - %Killer-3-Amount%'
  - ''
  - '&a&l-------------------------------'


############### REMOVE INVIS ON DAMAGE ###############

#Removes invis on specified damage causes
#I recommend you use this in combination with the Better Invisibility plugin.
#UPDATE: Better Invisibility may have this built in now, but this still works
Break-Invis:
  Enabled: true
  Causes:
    - ENTITY_ATTACK
    - BLOCK_EXPLOSION
    - ENTITY_EXPLOSION