############### PREVENT WATER BUILDUP ###############

#Prevents liquids from going outside BW arena
#Will not affect other gamemodes
Prevent-Liquid-Build-Up: true

############### HEIGHT CAP ###############

#Add a height cap for specific MBedwars arenas
#Add height cap like 'arenaName:70'
#To disable the message, set to ''
Height-Cap:
  Enabled: false
  Message: '&cYou cannot build any higher'
  Arenas:
    - ''

############### DEGRADED BUY-GROUPS ###############

Degraded-BuyGroups:
  Enabled: true
  Names:
    - 'pickaxe'

############### FINAL KILL ###############

#Adds FINAL KILL to the end of a message if the kill is Final
Final-Kill-Message: false

#Players get a lightning blot at their location of death if it is a final kill
Final-Kill-Strike:
  Enabled: false

############### FIREBALL BLOCK WHITELIST ###############

#Blocks that fireballs will not destroy (Overrides MBedwars' BlackList)
FireballWhitelist:
  Enabled: true
  Blocks:
    - ENDER_STONE
    - END_STONE

############### BUY-MESSAGE ###############

#Message sent to players when they purchase an item
#Placeholders: {amount} {product}
Buy-Message:
  Enabled: true
  Message: '&aYou Purchased &6{product} x{amount}'

############### DISABLE EMPTY BASE GENERATORS ###############

#Disable generators in empty bases
#Range = distance from team spawn to spawner
Disable-Unused-Gens:
  Enabled: false
  Range: 6
  Gen-Types:
    - 'IRON_INGOT'
    - 'GOLD_INGOT'

############### GEN TIERS ###############

#Teirs can be configured in the gen-tiers.yml
Gen-Tiers-Enabled: false

#Adds 'Tier I' to spawners listed
Tier-One-Titles:
  Tier-Name: '&eTier &cI'
  Spawners:
    - 'EMERALD'
    - 'DIAMOND'

#Message shown above spawners
# {spawner} {spawner-color} {time} {tier}
Spawner-Title:
  - '{tier}'
  - '{spawner-color}{spawner}'
  - '&eSpawning in &c{time} &eseconds!'

#PAPI Placeholder:
# {next-tier} {time}
Next-Tier-Placeholder: '{next-tier} in &a{time}'

############### BED BREAK ###############

#Message displayed when any bed is broken (to everyone in the arena)
Player-Destroy-Message:
  - ''
  - '&f&lBED DESTRUCTION > {team-color}{team-name} Bed &7was destroyed by {destroyer-color}{destroyer-name}'
  - ''

#Chat message displayed on Auto-Bed-Break
Auto-Destroy-Message:
  - ''
  - '&c&lALL BEDS HAVE BEEN DESTROYED'
  - ''

# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
Bed-Destroy-Sound: 'ENTITY_ENDER_DRAGON_GROWL'

#Title displayed to a player when his bed gets destroyed
#This replaces MBedwars' message, and only gets sent to the player with no bed
Notification:
  Big-Title: '&cBED DESTROYED'
  Small-Title: '&fYou will no longer respawn!'

############### TNT AUTO IGNITE ###############

#WARNING!!! If you enable this MAKE SURE MBedwars' tnt-autoignite is FALSE
TNT:
  Auto-Ignite: false
  Delay: 4

############### REMOVE ON USE ###############
Empty-Buckets: true
Empty-Potions: true

############### TOP KILLER MESSAGE ###############
Top-Killer-Message-Enabled: true

#No Top killers FinalKill
No-Top-Killers-Message:
  - ''

# PLACEHOLDERS:
# %Killer-1-Name% %Killer-2-Name% %Killer-3-Name%
# %Killer-1-Amount% %Killer-2-Amount% %Killer-3-Amount%
Top-Killer-Message:
  - '&a&l-------------------------------'
  - '                &lBedWars'
  - ''
  - '    &e&l1st Killer &7- %Killer-1-Name% - %Killer-1-Amount%'
  - '    &6&l2nd Killer &7- %Killer-2-Name% - %Killer-2-Amount%'
  - '    &c&l3rd Killer &7- %Killer-3-Name% - %Killer-3-Amount%'
  - ''
  - '&a&l-------------------------------'


############### REMOVE INVIS ON DAMAGE ###############

#Removes invis on specified damage causes
#I recommend you use this in combination with the Better Invisibility plugin.
#UPDATE: Better Invisibility may have this built in now, but this still works
Break-Invis:
  Enabled: true
  Causes:
    - ENTITY_ATTACK
    - BLOCK_EXPLOSION
    - ENTITY_EXPLOSION

############### Permanent Potion Effects ###############

#ArenaName:PotionEffectName:amplifier
#All arenas = ALL-ARENAS
Permanent-Effects:
  - 'Ruins:NIGHT_VISION'

############### Friendly Villagers ###############

#If this is enabled, MBedwars dealers/upgrade-dealers
#will look at the closest players
Friendly-Villagers: true